#!/bin/bash

# Run this script to connect to the VPN on a Linux system
# Move any openvpn config files to the ~/.vpn folder
# Example dev: ~/.vpn/github-dev-vpn.ovpn
# Example prod: github-iad-prod.visc/config.conf -> ~/.vpn/github-prod-vpn.ovpn

# Note: make sure to also copy your pkcs.p12 file to the ~/.vpn folder as well

set -e

VPN_DIR=~/.vpn
cd $VPN_DIR

missing () {
   echo "❌ Missing $VPN_DIR/$1 file"
   echo "Check out the docs: https://thehub.github.com/engineering/security/developer-vpn-access/linux/#openvpn-config"
   exit 1
}

[ ! -f ca.crt ] && missing "ca.crt"
[ ! -f ta.key ] && missing "ta.key"

if [[ $1 == "--dev" ]]; then
   echo -e "\n🧪 Connecting to the \033[0;32mDEV\033[0m GitHub VPN"
   config=~/.vpn/github-dev-vpn.ovpn
   [ ! -f github-dev-vpn.ovpn ] && missing "github-dev-vpn.ovpn"
elif [[ $1 == "--prod" ]]; then
   echo -e "\n🚀 Connecting to the \033[0;32mPROD\033[0m GitHub VPN"
   config=~/.vpn/github-prod-vpn.ovpn
   [ ! -f github-dev-vpn.ovpn ] && missing "github-prod-vpn.ovpn"
   [ ! -f pkcs.p12 ] && missing "pkcs.p12"
else
   echo -e "\n🚀 Connecting to the \033[0;32mPROD\033[0m GitHub VPN"
   config=~/.vpn/github-prod-vpn.ovpn
   [ ! -f pkcs.p12 ] && missing "pkcs.p12"
fi

echo -e "⌨️  Enter your \033[0;32msudo\033[0m password when prompted"

sudo openvpn --config $config --verb 1 --data-ciphers-fallback AES-128-CBC
