#!/bin/bash

# This script copies certificates into the directories that Viscosity for Windows requires
# It is designed to be run from a Windows Subsystem for Linux (WSL2) shell

set -e
set -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

# The user's WSL username could be different to their Windows username, so ask Windows what it is
# CMD.EXE complains about starting in a UNC path, so we pushd to C:\ and popd after to avoid the noise
WINDOWSUSERNAME="$(pushd /mnt/c > /dev/null; cmd.exe /C echo %username% |tr -d '\r'; popd > /dev/null)"

VISCOSITY_PROFILES_DIR="/mnt/c/Users/${WINDOWSUSERNAME}/AppData/Roaming/Viscosity/OpenVPN"

echo "Copying profiles and pkcs.p12 certificate from ${DIR} to ${VISCOSITY_PROFILES_DIR}"

# If Viscosity isn't installed yet, create the directory structure for the profiles
mkdir -p ${VISCOSITY_PROFILES_DIR}

# Each profile/connection is a separate directory
cp -r *.visc ${VISCOSITY_PROFILES_DIR}

# Copy our "make certificate" generated certificate into each profile
find ${VISCOSITY_PROFILES_DIR} -type d -exec cp "${DIR}/pkcs.p12" {} \;

if [[ ! -f "/mnt/c/Program Files/Viscosity/Viscosity.exe" ]]
then
    echo "Viscosity.exe does not appear to be installed."
    echo ""
    echo "Download from https://www.sparklabs.com/downloads/Viscosity%20Installer.exe"
    echo ""
    echo "Register using license key from https://gear.githubapp.com/apps/9"
    echo "For Windows, you don't need the email."
    echo "  Name: GitHub"
    echo "  Key:  VXG6..."
    echo ""
    echo "Once installed, all the profiles should be already installed and ready to go."
    echo ""
else
    # We need to restart viscosity client to refresh profiles
    echo "Stopping Viscosity.exe"
    pushd /mnt/c > /dev/null && cmd.exe /C taskkill /F /IM Viscosity.exe && popd > /dev/null

    echo "Starting Viscosity.exe"
    pushd /mnt/c > /dev/null && cmd.exe /C "start C:\Progra~1\Viscosity\Viscosity.exe" && popd > /dev/null
fi

echo "Developer VPN profile has NOT been installed"
echo "If you don't already have it, download & run it to import it from:"
echo "https://thehub.github.com/engineering/security/developer-vpn-access/github-iad-devvpn.visz?raw=true"
